fix: cicd

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -7,30 +7,71 @@ on:
 #    branches: [ master ]
 
 jobs:
-  build:
-
-    runs-on: ubuntu-latest
+  tests:
+    name: Running functional and unit test
+    runs-on: ubuntu-22.04
+    services:
+      mysql:
+        image: mysql:8.0
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_USER: dev
+          MYSQL_PASSWORD: dev
+          MYSQL_DATABASE: troctaplante
+        ports:
+          - 3306/tcp
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+    strategy:
+      fail-fast: true
+      matrix:
+        php-versions: [ '8.2-apache' ]
 
     steps:
-      - uses: actions/checkout@v2
+      # —— Setup Github actions 🐙 —————————————————————————————————————————————
+      # https://github.com/actions/checkout (official)
+      - name: Checkout
+        uses: actions/checkout@v2
 
-      - name: Setup PHP
+      # https://github.com/shivammathur/setup-php (community)
+      - name: Setup PHP, extensions and composer with shivammathur/setup-php
         uses: shivammathur/setup-php@v2
         with:
-          php-version: '8.2' # Change to your PHP version
-          extensions: mbstring, intl, pdo_mysql, curl # Add necessary extensions
-          coverage: pcov
+          php-version: ${{ matrix.php-versions }}
+          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, mysqli
+        env:
+          update: true
 
-      - name: Install dependencies
-        run: composer install --prefer-dist --no-progress --no-suggest
+      - name: Check PHP Version
+        run: php -v
 
-      - name: Cache dependencies
-        uses: actions/cache@v2
+
+        # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
+      - name: Validate composer.json and composer.lock
+        run: composer validate
+
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+
+      - name: Cache composer dependencies
+        uses: actions/cache@v1
         with:
-          path: ~/.composer/cache
+          path: ${{ steps.composer-cache.outputs.dir }}
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-composer-
+          restore-keys: ${{ runner.os }}-composer-
 
-      - name: Run PHPUnit tests
-        run: ./bin/phpunit
+      - name: Install Composer dependencies
+        run: composer install --no-progress --prefer-dist --optimize-autoloader
+
+      - run: composer require symfony/runtime
+
+      - name: Run Migration && Load Fixtures
+        run: |
+          composer require --dev symfony/orm-pack
+          php bin/console doctrine:database:drop --if-exists --force --env=test
+          php bin/console doctrine:database:create --if-not-exists --env=test
+          php bin/console doctrine:schema:update --env=test --force || echo "No migrations found or schema update failed"
+          php bin/console doctrine:migrations:migrate --env=test || echo "No migrations found or migration failed"
+          php bin/console doctrine:fixtures:load --no-interaction
+        env:
+          DATABASE_URL: mysql://dev:dev@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/troctaplante
