fix: add environnement

diff --git a/.github/workflows/recette.yml b/.github/workflows/recette.yml
--- a/.github/workflows/recette.yml
+++ b/.github/workflows/recette.yml
@@ -1,68 +1,69 @@
 on:
   pull_request:
-    branches: [ recette ]
+    branches: [recette]
 
 jobs:
-  # tests-unitaires:
-  #   name: Tests Unitaires
-  #   runs-on: ubuntu-22.04
-  #   # Permet d'utiliser une base de données pour les tests 
-  #   services:
-  #     mysql:
-  #       image: mysql:8.0
-  #       env:
-  #         MYSQL_ALLOW_EMPTY_PASSWORD: false
-  #         MYSQL_USER: dev
-  #         MYSQL_PASSWORD: dev
-  #         MYSQL_DATABASE: troctaplante
-  #       ports:
-  #         - 3306:3306
-  #       options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+  tests-unitaires:
+    name: Tests Unitaires
+    runs-on: ubuntu-22.04
+    # Permet d'utiliser une base de données pour les tests
+    services:
+      mysql:
+        image: mysql:8.0
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_USER: dev
+          MYSQL_PASSWORD: dev
+          MYSQL_DATABASE: troctaplante
+        ports:
+          - 3306:3306
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
-  #   steps:
-  #     # Récupération du code source
-  #     - name: Récupération du code source dans le container 
-  #       uses: actions/checkout@v2
+    steps:
+      # Récupération du code source
+      - name: Récupération du code source dans le container
+        uses: actions/checkout@v2
 
-  #     - name: Configuration de PHP
-  #       uses: shivammathur/setup-php@v2
-  #       with:
-  #         php-version: ${{ matrix.php-versions }}
-  #         extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, mysqli
-  #       env:
-  #         update: true
+      - name: Configuration de PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: ${{ matrix.php-versions }}
+          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, mysqli
+        env:
+          update: true
 
-  #     - name: Récupération de Composer
-  #       id: composer-cache
-  #       run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+      - name: Récupération de Composer
+        id: composer-cache
+        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
 
-  #     - name: Mise en cache des dépendances de Composer
-  #       uses: actions/cache@v1
-  #       with:
-  #         path: ${{ steps.composer-cache.outputs.dir }}
-  #         key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-  #         restore-keys: ${{ runner.os }}-composer-
+      - name: Mise en cache des dépendances de Composer
+        uses: actions/cache@v1
+        with:
+          path: ${{ steps.composer-cache.outputs.dir }}
+          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+          restore-keys: ${{ runner.os }}-composer-
 
-  #     - name: Installation des dépendances de Composer
-  #       run: composer install
+      - name: Installation des dépendances de Composer
+        run: composer install
 
-  #     - run: composer require symfony/runtime
+      - run: composer require symfony/runtime
 
-  #     - name: Création de la base de données et exécution des migrations
-  #       run: |
-  #         composer require --dev symfony/orm-pack
-  #         php bin/console doctrine:database:drop --if-exists --force
-  #         php bin/console doctrine:database:create --if-not-exists
-  #         php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
-  #       env:
-  #         DATABASE_URL: mysql://dev:dev@127.0.0.1:3306/troctaplante
+      - name: Création de la base de données et exécution des migrations
+        run: |
+          composer require --dev symfony/orm-pack
+          php bin/console doctrine:database:drop --if-exists --force
+          php bin/console doctrine:database:create --if-not-exists
+          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        env:
+          DATABASE_URL: mysql://dev:dev@127.0.0.1:3306/troctaplante
 
-  #     - name: Lancement des tests unitaires
-  #       run: php bin/phpunit
-  #       env:
-  #         DATABASE_URL: mysql://dev:dev@127.0.0.1:3306/troctaplante
+      - name: Lancement des tests unitaires
+        run: php bin/phpunit
+        env:
+          DATABASE_URL: mysql://dev:dev@127.0.0.1:3306/troctaplante
 
   build-docker:
+    environment: recette
     needs: tests-unitaires
     name: Création de l'image Docker
     runs-on: ubuntu-22.04 #Mettre ubuntu-latest revient au même
